# Automatically generated by pb2py
from trezorlib import protobuf as p
t = p.MessageType('DebugLinkMemoryRead')
t.wire_type = 110
t.add_field(1, 'address', p.UVarintType)
t.add_field(2, 'length', p.UVarintType)
DebugLinkMemoryRead = t