# Automatically generated by pb2py
from trezorlib import protobuf as p
t = p.MessageType('DebugLinkMemoryWrite')
t.wire_type = 112
t.add_field(1, 'address', p.UVarintType)
t.add_field(2, 'memory', p.BytesType)
t.add_field(3, 'flash', p.BoolType)
DebugLinkMemoryWrite = t