# Automatically generated by pb2py
from trezorlib import protobuf as p
t = p.MessageType('EthereumGetAddress')
t.wire_type = 56
t.add_field(1, 'address_n', p.UVarintType, flags=p.FLAG_REPEATED)
t.add_field(2, 'show_display', p.BoolType)
EthereumGetAddress = t