# Automatically generated by pb2py
from trezorlib import protobuf as p
t = p.MessageType('EthereumAddress')
t.wire_type = 57
t.add_field(1, 'address', p.BytesType, flags=p.FLAG_REQUIRED)
EthereumAddress = t