# Automatically generated by pb2py
from trezorlib import protobuf as p

t = p.MessageType('EthereumTxRequest')
t.wire_type = 59
t.add_field(1, 'data_length', p.UVarintType)
t.add_field(2, 'signature_v', p.UVarintType)
t.add_field(3, 'signature_r', p.BytesType)
t.add_field(4, 'signature_s', p.BytesType)
EthereumTxRequest = t