# Automatically generated by pb2py
from trezorlib import protobuf as p
from .IdentityType import IdentityType

t = p.MessageType('GetECDHSessionKey')
t.wire_type = 61
t.add_field(1, 'identity', p.EmbeddedMessage(IdentityType))
t.add_field(2, 'peer_public_key', p.BytesType)
t.add_field(3, 'ecdsa_curve_name', p.UnicodeType)
GetECDHSessionKey = t